---
- name: Create a VM from a template
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - name: Clone the template
    vmware_guest:
      hostname: 10.10.124.9
      username: administrator@vsphere.local
      password: HP1nvent!
      validate_certs: False
      name: "{{ vmname }}"
      template: Wind2019JumpVM-Terraform
      datacenter: INTEL_DC
      folder: /INTEL_DC/vm
      state: poweredon
      wait_for_ip_address: no

